spring:
  application:
    name: rate-printer

grpc:
  client:
    currency-rate-provider:
      address: static://localhost:9090
      negotiation-type: plaintext

rate-printer:
  from-currency: USD
  to-currency: RUB
  poll-interval-ms: 5000